[package]
name = "rsms"
version = "0.0.1"
edition = "2021"
authors = ["zhangkaric@gmail.com"]
license = "MIT"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "rsms"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
actix-web = "4"
